@startuml Face2D
scale 2
title "UML Class Diagram"

class Face2D {
    .. Instance Variables ..
    - _points: List[Point]
    - _distance: float
    - _color: Shader
    .. Properties ..
    + points: List[Point] {get; set;}
    + distance: float {get;}
    + color: Shader {get; set;}
    .. Constructor ..
    + __init__(points: List[Point], dist: float, color: Shader): None
    .. Comparison Methods ..
    + __lt__(other: object): bool
    + __gt__(other: object): bool
    + __ge__(other: object): bool
    + __le__(other: object): bool
    .. Other Methods ..
    + __repr__(): str
}
@enduml
