@startuml Point
scale 2
title "UML Class Diagram"

class Point {
    .. Instance Variables ..
    - _x: int
    - _y: int
    - _z: int
    .. Properties ..
    + x: int {get; set;}
    + y: int {get; set;}
    + z: int {get; set;}
    .. Overloaded Methods ..
    + __init__(x: int, y: int, z: int): None
    + __eq__(other: object): bool
}
@enduml
